ALTER TABLE "public"."profiles"
  DROP COLUMN "avatar_url";

ALTER TABLE "public"."profiles"
  DROP COLUMN "website";

CREATE TABLE "public"."announcements" (
  "id"               bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"       timestamp with time zone    NOT NULL DEFAULT now(),
  "name"             text,
  "category"         text,
  "announcement_end" timestamp without time zone,
  CONSTRAINT "announcements_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."announcements"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."church_lessons" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "series_id"     bigint                   NOT NULL,
  "lesson_number" bigint                   NOT NULL,
  "lesson_id"     bigint,
  CONSTRAINT "church_lessons_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."church_lessons"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."devotion_lessons" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "odb_link"   text                     NOT NULL,
  "title"      text,
  "date"       date                     NOT NULL,
  "lesson_id"  bigint,
  CONSTRAINT "devotion_lessons_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."devotion_lessons"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event_availabilities" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text,
  CONSTRAINT "event_availabilities_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."event_availabilities"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."events" (
  "id"                bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"        timestamp with time zone    NOT NULL DEFAULT now(),
  "title"             text,
  "timestamp"         timestamp without time zone,
  "location"          text,
  "repeat_every_days" bigint,
  "announcement_end"  timestamp without time zone,
  "information"       text,
  CONSTRAINT "events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."lessons_events_link" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "livestream_link"   text,
  "is_live"           boolean,
  "lessons_events_id" bigint,
  CONSTRAINT "lessons_events_link_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."lessons_events_link"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."lessons_events_slides" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "slides_link"       text,
  "lessons_events_id" bigint,
  CONSTRAINT "lessons_events_slides_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."lessons_events_slides"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."lessons_events_speakers" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "lessons_events_id" bigint,
  "speaker_user_id"   uuid,
  CONSTRAINT "lessons_events_speakers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."lessons_events_speakers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."lessons_events" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "lesson_id"  bigint,
  "event_id"   bigint,
  CONSTRAINT "lessons_events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."lessons_events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."lessons" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "title"      text,
  "tags"       json,
  CONSTRAINT "lessons_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."lessons"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."life_group_events_members" (
  "id"                    bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "event_availability_id" bigint,
  "life_group_event_id"   bigint,
  "member_user_id"        uuid,
  CONSTRAINT "life_group_events_members_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_group_events_members"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."life_group_events" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "creator_user_id" uuid,
  "event_id"        bigint,
  CONSTRAINT "life_group_events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_group_events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."life_group_members" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "is_admin"           boolean,
  "life_group_id"      bigint,
  "member_user_id"     uuid,
  "life_group_role_id" bigint,
  CONSTRAINT "life_group_members_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_group_members"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."life_group_roles" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text,
  CONSTRAINT "life_group_roles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_group_roles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."life_groups" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text,
  CONSTRAINT "life_groups_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_groups"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."series" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "name"          text,
  "lesson_number" bigint,
  "track_id"      bigint                   NOT NULL,
  CONSTRAINT "series_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."series"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tracks" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text,
  "heading"    text,
  CONSTRAINT "tracks_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tracks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users_lessons_completion" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"    uuid                     NOT NULL,
  "lesson_id"  bigint                   NOT NULL,
  CONSTRAINT "users_lessons_completion_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users_lessons_completion"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users_lessons" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "notes"      text,
  "tags"       json,
  "user_id"    uuid,
  "lesson_id"  bigint,
  CONSTRAINT "users_lessons_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users_lessons"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles"
  ADD COLUMN "avatar_link" text;

ALTER TABLE "public"."profiles"
  ADD COLUMN "faecbook_link" text;

ALTER TABLE "public"."profiles"
  ADD COLUMN "instagram_link" text;

ALTER TABLE "public"."profiles"
  ADD COLUMN "birthday" date;

ALTER TABLE "public"."profiles"
  ADD COLUMN "track_id" bigint;

ALTER TABLE "public"."church_lessons"
  ADD CONSTRAINT "church_lessons_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."devotion_lessons"
  ADD CONSTRAINT "devotion_lessons_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."lessons_events"
  ADD CONSTRAINT "lessons_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id);

ALTER TABLE "public"."lessons_events"
  ADD CONSTRAINT "lessons_events_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."lessons_events_link"
  ADD CONSTRAINT "lessons_events_link_lessons_events_id_fkey" FOREIGN KEY (lessons_events_id) REFERENCES public.lessons_events(id);

ALTER TABLE "public"."lessons_events_slides"
  ADD CONSTRAINT "lessons_events_slides_lessons_events_id_fkey" FOREIGN KEY (lessons_events_id) REFERENCES public.lessons_events(id);

ALTER TABLE "public"."lessons_events_speakers"
  ADD CONSTRAINT "lessons_events_speakers_lessons_events_id_fkey" FOREIGN KEY (lessons_events_id) REFERENCES public.lessons_events(id);

ALTER TABLE "public"."lessons_events_speakers"
  ADD CONSTRAINT "lessons_events_speakers_speaker_user_id_fkey" FOREIGN KEY (speaker_user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_events"
  ADD CONSTRAINT "life_group_events_creator_user_id_fkey" FOREIGN KEY (creator_user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_events"
  ADD CONSTRAINT "life_group_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id);

ALTER TABLE "public"."life_group_events_members"
  ADD CONSTRAINT "life_group_events_members_event_availability_id_fkey" FOREIGN KEY (event_availability_id) REFERENCES public.event_availabilities(id);

ALTER TABLE "public"."life_group_events_members"
  ADD CONSTRAINT "life_group_events_members_life_group_event_id_fkey" FOREIGN KEY (life_group_event_id) REFERENCES public.life_group_events(id);

ALTER TABLE "public"."life_group_events_members"
  ADD CONSTRAINT "life_group_events_members_member_user_id_fkey" FOREIGN KEY (member_user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_members"
  ADD CONSTRAINT "life_group_members_member_user_id_fkey" FOREIGN KEY (member_user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_members"
  ADD CONSTRAINT "life_group_members_life_group_role_id_fkey" FOREIGN KEY (life_group_role_id) REFERENCES public.life_group_roles(id);

ALTER TABLE "public"."life_group_members"
  ADD CONSTRAINT "life_group_members_life_group_id_fkey" FOREIGN KEY (life_group_id) REFERENCES public.life_groups(id);

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_track_id_fkey" FOREIGN KEY (track_id) REFERENCES public.tracks(id);

ALTER TABLE "public"."series"
  ADD CONSTRAINT "series_track_id_fkey" FOREIGN KEY (track_id) REFERENCES public.tracks(id);

ALTER TABLE "public"."users_lessons"
  ADD CONSTRAINT "users_lessons_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."users_lessons"
  ADD CONSTRAINT "users_lessons_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."users_lessons_completion"
  ADD CONSTRAINT "users_lessons_completion_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."users_lessons_completion"
  ADD CONSTRAINT "users_lessons_completion_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

COMMENT ON COLUMN "public"."profiles"."track_id" IS 'The highest track the user is allowed to access';

COMMENT ON COLUMN "public"."tracks"."heading" IS '"Week", "Heading", etc.';

COMMENT ON TABLE "public"."users_lessons" IS 'Stores user notes per lesson';

REVOKE ALL ON SEQUENCE "public"."announcements_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."announcements_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."announcements_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."announcements_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."announcements_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."announcements_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."announcements_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."announcements_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."church_lessons_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."church_lessons_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."church_lessons_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."church_lessons_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."church_lessons_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."church_lessons_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."church_lessons_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."church_lessons_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."devotion_lessons_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."devotion_lessons_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."devotion_lessons_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."devotion_lessons_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."devotion_lessons_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."devotion_lessons_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."devotion_lessons_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."devotion_lessons_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."event_availabilities_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."event_availabilities_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."event_availabilities_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."event_availabilities_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."event_availabilities_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."event_availabilities_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."event_availabilities_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."event_availabilities_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."lessons_events_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."lessons_events_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."lessons_events_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."lessons_events_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."lessons_events_link_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_link_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."lessons_events_link_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_link_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."lessons_events_link_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_link_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."lessons_events_link_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_link_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."lessons_events_slides_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_slides_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."lessons_events_slides_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_slides_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."lessons_events_slides_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_slides_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."lessons_events_slides_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_slides_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."lessons_events_speakers_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_speakers_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."lessons_events_speakers_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_speakers_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."lessons_events_speakers_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_speakers_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."lessons_events_speakers_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_events_speakers_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."lessons_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."lessons_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."lessons_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."lessons_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."lessons_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."life_group_events_members_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_members_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_group_events_members_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_members_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_group_events_members_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_members_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_group_events_members_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_members_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."life_group_members_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_members_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_group_members_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_members_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_group_members_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_members_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_group_members_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_members_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."life_group_roles_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_roles_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_group_roles_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_roles_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_group_roles_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_roles_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_group_roles_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_roles_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."life_groups_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_groups_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_groups_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_groups_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_groups_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_groups_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_groups_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_groups_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."series_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."series_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."series_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."series_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."series_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."series_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."series_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."series_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."tracks_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tracks_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."tracks_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tracks_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."tracks_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tracks_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."tracks_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tracks_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."users_lessons_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."users_lessons_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."users_lessons_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."users_lessons_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."announcements" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."church_lessons" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."church_lessons" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."church_lessons" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."church_lessons" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."devotion_lessons" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."devotion_lessons" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."devotion_lessons" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."devotion_lessons" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_availabilities" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."event_availabilities" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_availabilities" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_availabilities" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."lessons" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."lessons_events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_link" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."lessons_events_link" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_link" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_link" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_slides" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."lessons_events_slides" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_slides" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_slides" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_speakers" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."lessons_events_speakers" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_speakers" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."lessons_events_speakers" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_group_events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events_members" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_group_events_members" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events_members" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events_members" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_members" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_group_members" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_members" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_members" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_roles" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_group_roles" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_roles" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_roles" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_groups" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_groups" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_groups" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_groups" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."series" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."series" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."series" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."series" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tracks" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."tracks" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tracks" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tracks" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."users_lessons" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completion" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."users_lessons_completion" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completion" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completion" TO "service_role";

