CREATE TABLE "public"."life_group_events" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "event_id"      bigint                   NOT NULL,
  "life_group_id" bigint                   NOT NULL,
  CONSTRAINT "life_group_events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."life_group_events"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."life_group_events"
  ADD CONSTRAINT "life_group_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id);

ALTER TABLE "public"."life_group_events"
  ADD CONSTRAINT "life_group_events_life_group_id_fkey" FOREIGN KEY (life_group_id) REFERENCES public.life_groups(id);

CREATE UNIQUE INDEX idx_life_group_events_event_id_life_group_id ON public.life_group_events USING btree (event_id, life_group_id);

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."life_group_events_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."life_group_events_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."life_group_events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."life_group_events" TO "service_role";
