ALTER TABLE "public"."lessons_events_speakers"
  DROP CONSTRAINT "lessons_events_speakers_speaker_user_id_fkey";

ALTER TABLE "public"."life_group_events_members"
  DROP CONSTRAINT "life_group_events_members_member_user_id_fkey";

ALTER TABLE "public"."life_group_members"
  DROP CONSTRAINT "life_group_members_member_user_id_fkey";

ALTER TABLE "public"."users_lessons_completion"
  DROP CONSTRAINT "users_lessons_completion_lesson_id_fkey";

ALTER TABLE "public"."users_lessons_completion"
  DROP CONSTRAINT "users_lessons_completion_user_id_fkey";

ALTER TABLE "public"."lessons_events_speakers"
  DROP COLUMN "speaker_user_id";

ALTER TABLE "public"."life_group_events_members"
  DROP COLUMN "member_user_id";

ALTER TABLE "public"."life_group_members"
  DROP COLUMN "member_user_id";

ALTER TABLE "public"."series"
  DROP COLUMN "lesson_number";

DROP TABLE "public"."users_lessons_completion";

CREATE TABLE "public"."users_lessons_completions" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."users_lessons_completion_id_seq") NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"      uuid                     NOT NULL,
  "lesson_id"    bigint                   NOT NULL,
  "is_completed" boolean,
  CONSTRAINT "users_lessons_completion_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users_lessons_completions"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."lessons_events_speakers"
  ADD COLUMN "user_id" uuid;

ALTER TABLE "public"."life_group_events_members"
  ADD COLUMN "user_id" uuid;

ALTER TABLE "public"."life_group_members"
  ADD COLUMN "user_id" uuid;

ALTER TABLE "public"."series"
  ADD COLUMN "series_number" bigint;

ALTER TABLE "public"."lessons_events_speakers"
  ADD CONSTRAINT "lessons_events_speakers_speaker_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_events_members"
  ADD CONSTRAINT "life_group_events_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."life_group_members"
  ADD CONSTRAINT "life_group_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."users_lessons_completions"
  ADD CONSTRAINT "users_lessons_completion_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

ALTER TABLE "public"."users_lessons_completions"
  ADD CONSTRAINT "users_lessons_completion_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

CREATE UNIQUE INDEX idx_church_lessons_lesson_id ON public.church_lessons USING btree (lesson_id);

CREATE UNIQUE INDEX idx_church_lessons_series_id_lesson_number ON public.church_lessons USING btree (series_id, lesson_number);

CREATE UNIQUE INDEX idx_devotion_lessons_lesson_id ON public.devotion_lessons USING btree (lesson_id);

CREATE UNIQUE INDEX idx_devotion_lessons_odb_link_date ON public.devotion_lessons USING btree (odb_link, date);

CREATE UNIQUE INDEX idx_lessons_events_lesson_id_event_id ON public.lessons_events USING btree (lesson_id, event_id);

CREATE UNIQUE INDEX idx_lessons_events_link_lessons_events_id_livestream_link ON public.lessons_events_link USING btree (lessons_events_id, livestream_link);

CREATE UNIQUE INDEX idx_life_group_events_event_id ON public.life_group_events USING btree (event_id);

CREATE UNIQUE INDEX idx_life_group_events_members_all ON public.life_group_events_members USING btree (event_availability_id, life_group_event_id, user_id);

CREATE UNIQUE INDEX idx_life_group_members_member_user_id_life_group_id ON public.life_group_members USING btree (user_id, life_group_id);

CREATE UNIQUE INDEX idx_series_series_number_track_id ON public.series USING btree (series_number, track_id);

CREATE UNIQUE INDEX idx_users_lessons_completions_user_id_lesson_id ON public.users_lessons_completions USING btree (user_id, lesson_id);

CREATE UNIQUE INDEX idx_users_lessons_user_id_lesson_id ON public.users_lessons USING btree (user_id, lesson_id);

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."users_lessons_completion_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."users_lessons_completion_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completions" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."users_lessons_completions" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completions" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users_lessons_completions" TO "service_role";
